
// langues
document.addEventListener('DOMContentLoaded', function() {
var elems = document.querySelectorAll('.dropdown-trigger');
var instances = M.Dropdown.init(elems, {"constrainWidth":true, "alignment":"left"});
});

i18next.init({
    lng: 'EN',
    resources: {
      EN: {
        translation: {
          title : "My Ile-de-France Map",
          AccueilofNav: "Home",
          TutorielofNav: "Tutorial",
          MymapofNav :"MY MAP",
          MyplacesofNav : "MY PLACES",
          DiscoverOfNav:"Discover other maps",
          shortDescription:"Create your own personalised map of Ile-de-France, take the time to rediscover your region",
          buttonExample : "See example",
          subtitle1 : "Summary",
          text1 : " is an online tool that allows you to record your points of interest in the region and the information associated with them. Once the map is created, a system of filters allows you to easily view your addresses.",
          subtitle2 : "How does it work?",
          text2 : "Find a detailed step-by-step tutorial, accessible to young and old alike, to create your personalised map of Ile de France.",
          subtitle3 : "Your maps!",
          text3 : "Send us your map files with your first name by email to see your map appear on the site. Thus, let us enrich together the good addresses of the Ile de France region!",
            page2Title : "5 steps to make my map",
            page2comment : "We publish the maps you send us",
            page2titre1 : "What you need to know before making your map",
            page2titre2 : "Create an empty map",
            page2titre3 : "Add places",
            page2titre4 : "Visualize and Filter",
            page2titre5 : "Save and reload",
           page2text1a : "To position points on a map, we use geographical coordinates which are",
           page2text1b : " and",
           Majlatitude : "Latitude",
           latitude : "latitude",
           page2text1d :"gives us whether a point is to the WEST or EAST of the globe in relation to the Greenwich meridian. This landmark, located in England, defines the longitude 0°. Points to the EAST have a longitude between 0° and 180° while to the WEST, the longitude is negative up to -180°.",
           page2text1e : "tells us whether a point is NORTH or SOUTH of the equator. The equator defines the latitude 0°. The latitude is between 0° and 180° for the NORTH and goes down to -180° for the SOUTH.",
           page2textexample : "Example:",
           longitude : "longitude",
           Majlongitude : "Longitude",
           page2text2 : "Lisbon is located WEST of the Greenwich Meridian. Its longitude is then less than 0°. Indeed, the longitude of Lisbon is -9.13°. Lisbon is well NORTH of the equator. Its latitude is then greater than 0°. Indeed, the longitude of Lisbon is 38.70°.",
        page2text3a : "When you click on ",
        page2text3b : "a set of dots is displayed. This is the ",
        page2text3c : "Laboratoires d'île de France",
        page2text3d : "This map is an example.",
          page2text3e : "To start your map, go to the tab ",
          page2text3f : "click on the trash can",
          page2text3g : "to delete existing points and start your map!",
          page2text4a : "Three elements are essential to add points to your map: a",
          page2text4b : "unique name",
          page2text4c : "However, you have the possibility to add additional information using the button",
          page2text4d : "How to find the coordinates of the places?",
          page2text4e : "Many sites give the geographical coordinates from  the address. You can use for example :",
          page2text5a : "Once you have created a certain number of addresses, you can view your map by clicking directly on tab",
          page2text5b : "You can filter the results according to the columns you have filled!",
            page2text6a : "Please note that we do not store any data that you enter. To keep your data, you must ",
            page2text6b : "click on",
            page2text6c: "A file is created.",
            page2text6d : "To load previous works, click on",
            page2text6e : "and select your file",
            page2text6f : "save your map",
            page2text6g : "Well done! You enrich our region by creating maps of good addresses!",
            page2text6h : "If you would like your map to be available on this website, please send it to ",
            anda : " and a ",
            a : "a",
            context : "Context",
            thetool : "The tool ",
            thetoolb : "has been developed in the context of ",
            thetoolc : "The Ile-de-France region organizes this competition for students in international mobility in order to provide them with financial assistance. This award is then intended for participants who have participated in highlighting the wealth of the Ile-de-France region",
            by : "By:",
            help: "Technical help",
            creator: "Creator",
            confidentialite : "Confidentiality: the information entered is only stored on your browser, we do not have access to it.",
            listOfMaps : "Here is a nice list of maps, made by users, for your greatest pleasure. Browse through different types of projects, get inspired to make your own map or simply discover new places."


        }
       },
       FR: {
          translation: {
           title : "Ma Carte d'Ile-de-France",
           AccueilofNav: "Accueil",
           TutorielofNav: "Tutoriel",
           MymapofNav : "MA CARTE",
           MyplacesofNav : "MES LIEUX",
           DiscoverOfNav:"Découvrir des cartes",
           shortDescription:"Créer sa carte personnalisée d'île-de-France, prendre le temps de redécouvrir sa région",
           buttonExample: "Voir l'exemple",
           subtitle1 : "Présentation",
           text1 : " est un outil en ligne vous permettant d'enregistrer vos points d'intérêt dans la région et les informations associées à ces points. Une fois la carte créée, un système de filtres vous permet de visualiser aisément vos adresses.",
           subtitle2: "Comment ça marche ?",
           text2 : "Trouvez un tutoriel détaillé étape par étape, accessible aux plus jeunes comme aux anciens, pour créer votre carte personnalisée d'île de France.",
           subtitle3:"Vos cartes !",
           text3 : "Envoyez-nous vos fichiers de carte avec votre prénom par email afin de voir votre carte apparaître sur le site. Ainsi, enrichissons ensemble les bonnes adresses de la région d'île de France !",
           page2Title: "Faire ma carte en 5 étapes",
           page2comment :"Nous publions les cartes que vous nous envoyez.",
           page2titre1 : "Ce qu'il faut savoir avant de faire sa carte",
           page2titre2 : "Créer une carte vierge",
           page2titre3 : "Ajouter des points",
           page2titre4 : "Visualiser et filtrer",
           page2titre5 : "Enregistrer et recharger",
           page2text1a : "Pour positionner des points sur une carte, on utilise des coordonnées géographique qui sont la",
           page2text1b : "et la",
           page2text1c : "La",
           page2text1d : "nous indique si un point est à l'OUEST ou à l'EST du globe par rapport au méridien de Greenwich. Ce repère, situé en Angleterre, définit la longitude 0°. Les points à l'EST ont une longitude entre 0° et 180° tandis qu'à l'OUEST, la longitude est négative jusqu'à -180°.",
           page2text1e : "nous indique si un point est au NORD ou au SUD par rapport à l'équateur. L'équateur définit la latitude 0°. La latitude est entre 0° et 180° pour le NORD et descends jusqu'à -180° pour le SUD.",
           page2textexample : "Exemple:",
           Majlatitude : "La latitude",
           latitude : " la latitude",
           longitude :"la longitude",
           Majlongitude : "La longitude",
           page2text2 : "Lisbonne se trouve à l'OUEST du méridien de Greenwich. Sa longitude est alors inférieure à 0°. En effet, la longitude de Lisbonne est -9,13°. Lisbonne est bien au NORD de l'équateur. Sa latitude est alors supérieure à 0°. En effet, la longitude de Lisbonne est 38.70°.",
            page2text3a : "Lorsque vous cliquez sur l'onglet",
            page2text3b : " un ensemble de points s'affiche. C'est la carte des ",
            page2text3c : "Laboratoires d'île de France",
            page2text3d : "Cette carte est un exemple.",
            page2text3e : "Pour commencer votre carte, allez dans l'onglet ",
            page2text3f : "cliquez sur la poubelle",
            page2text3g : "pour supprimer les points existants et commencer votre carte!",
            page2text4a : "Trois élements sont essentiels pour ajouter des points sur votre carte: un",
            page2text4b : "nom unique",
            page2text4c : "Cependant vous avez la possibilité d'ajouter des informations suppémentaires à l'aide du bouton",
            page2text4d :"Comment trouver les coordonnées des points?",
            page2text4e : "De nombreux sites donnent les coordonnées géographiques grâce à l'adresse. Vous pouvez utiliser par exemple :",
            page2text5a : "Une fois que vous avez rentré un certain nombre de points, vous pouvez visualiser votre carte en cliquant directement sur l'onglet",
            page2text5b : "Vous pouvez filter les resultats en fonction des colonnes que vous avez enregistré!",
            page2text6a : "Attention, nous ne stockons aucune donnée que vous enregistrez. Pour garder vos données, il faut ",
            page2text6b : "en cliquant sur",
            page2text6c : "Un fichier est alors généré.",
            page2text6d : "Pour charger vos anciens points, utilisez le bouton",
            page2text6e : "et selectionnez votre fichier",
            page2text6f : "enregistrer votre carte",
            page2text6g : "Bravo! Vous enrichissez notre région en créant des cartes de bonnes adresses!",
            page2text6h : "Si vous souhaitez que votre carte soit disponible sur ce site web, veuillez l'envoyer à l'adresse : ",
            anda : " et une",
            a : "une",
            context : "Contexte du projet",
            thetool : "L'outil ",
            thetoolb : "a été développée dans le cadre des ",
            thetoolc : "La région d'île de France organise ce concours destiné aux étudiants en mobilité internationale afin de leur apporter une aide financière. Cette récompense est alors destinée aux participants ayant participer à la mise en valeur de la richesse de la région d'île de France",

            by : "Par:",
            creator: "Créateur",
            help: "Aide technique",
            confidentialite : "Confidentialité: les informations rentrées sont uniquement stockées sur votre navigateur, nous n'y avons pas accès.",
            listOfMaps : "Voici une belle liste de cartes, faites par des utilisateurs, pour votre plus grand plaisir. Parcourez différents types de projets, inspirez vous pour faire votre propre carte ou simplement découvrir de nouveaux lieux."
          }
        },
        ES : {
            translation : {
            title : "Mi mapa de Ile-de-France",
           AccueilofNav: "Inicio",
           TutorielofNav: "Tutorial",
           MymapofNav : "MI MAPA",
           MyplacesofNav : "MIS LUGARES",
           DiscoverOfNav:"Descubrir los mapas",
           shortDescription:"Cree su mapa personalizado de Ile-de-France, tómese su tiempo para redescubrir su región",
           buttonExample: "Vea el ejemplo",
           subtitle1 : "Presentación",
           text1 : " es una herramienta en línea que permite registrar sus puntos de interés en la región y la información asociada a ellos. Una vez creado el mapa, un sistema de filtros le permite ver fácilmente sus direcciones.",
           subtitle2: "¿Cómo funciona?",
           text2 : "Encuentre un tutorial detallado paso a paso, accesible a jóvenes y mayores, para crear su mapa personalizado de Ile-de-France.",
           subtitle3:"¡Tus mapas!",
           text3 : "Envíenos los archivos de su tarjeta con su nombre de pila por correo electrónico para ver su tarjeta aparecer en el sitio. Así, enriquezcamos juntos las buenas direcciones de la región de Ile-de-France!",
           page2Title: "Haz mi tarjeta en 5 pasos",
           page2comment :"Publicamos las tarjetas que nos envías.",
           page2titre1 : "Lo que necesitas saber antes de hacer tu tarjeta",
           page2titre2 : "Crear un mapa vacío",
           page2titre3 : "Agregar direcciones",
           page2titre4 : "Ver y filtrar",
           page2titre5 : "Guardar y recargar",
           page2text1a : "Para posicionar los puntos en un mapa, usamos coordenadas geográficas que son la",
           page2text1b : "y el",
           page2text1c : "El",
           page2text1d : "nos dice si un punto es OESTE o ESTE del globo en relación con el Meridiano de Greenwich. Este hito, situado en Inglaterra, define la longitud 0°. Los puntos al ESTE tienen una longitud entre 0° y 180° mientras que al OESTE, la longitud es negativa hasta -180°.",
           page2text1e : "nos dice si un punto está al NORTE o al SUR del ecuador. El ecuador define la latitud 0°. La latitud está entre 0° y 180° para el NORTE y baja a -180° para el SUR.",
           page2textexample : "Ejemplo:",
           Majlatitude : "Latitud",
           latitude : " atitud",
           longitude :" longitud",
           Majlongitude : "Longitud",
           page2text2 : "Lisboa está situada al OESTE del Meridiano de Greenwich. Su longitud es entonces menos de 0°. De hecho, la longitud de Lisboa es de -9,13°. Lisboa está bien al NORTE del ecuador. Su latitud es entonces más alta que 0°. De hecho, la longitud de Lisboa es de 38,70°.",
            page2text3a : "Cuando haces clic en el",
            page2text3b : " se muestra un conjunto de puntos. Este es el ",
            page2text3c : "Laboratoires d'île de France",
            page2text3d : "Esta tarjeta es un ejemplo.",
            page2text3e : "Para iniciar su tarjeta, vaya a la pestaña ",
            page2text3f : "haga clic en el cubo de basura",
            page2text3g : "para borrar los puntos existentes e iniciar el mapa!",
            page2text4a : "Tres elementos son esenciales para añadir puntos a su mapa: un",
            page2text4b : "nombre único",
            page2text4c : "Sin embargo, tiene la posibilidad de añadir información adicional utilizando el botón",
            page2text4d :"¿Cómo encuentro las coordenadas de los puntos?",
            page2text4e : "Muchos sitios dan las coordenadas geográficas a través de la dirección. Puedes usar por ejemplo..:",
            page2text5a : "Una vez que haya introducido un cierto número de puntos, puede ver su mapa haciendo clic directamente en la pestaña",
            page2text5b : "¡Puedes filtrar los resultados según las columnas que has guardado!",
            page2text6a : "Por favor, tenga en cuenta que no almacenamos ningún dato que usted registre. Para mantener sus datos, debe ",
            page2text6b : "haciendo clic en",
            page2text6c : "Entonces se genera un archivo.",
            page2text6d : "Para cargar tus viejos puntos, usa el",
            page2text6e : "y seleccione su archivo",
            page2text6f : "registre su tarjeta",
            page2text6g : "¡Bravo! ¡Enriquecen nuestra región creando mapas de buenas direcciones!",
            page2text6h : "Si desea que su tarjeta esté disponible en este sitio web, por favor envíela a : ",
            anda : " y un",
            a : "un",
            context : "Antecedentes del proyecto",
            thetool : "La herramienta ",
            thetoolb : "fue desarrollado como parte de la ",
            thetoolc : "La región de Ile-de-France organiza este concurso para los estudiantes en movilidad internacional con el fin de proporcionarles una ayuda financiera. Este premio está destinado a los participantes que hayan contribuido a la valorización de la riqueza de la región de Ile-de-France.",

            by : "Por:",
            creator: "Creador",
            help: "Soporte técnico",
            confidentialite : "Confidencialidad: la información introducida sólo se almacena en su navegador, no tenemos acceso a ella.",
            listOfMaps : "Aquí hay una bonita lista de tarjetas, hechas por los usuarios, para su mayor placer. Navega a través de diferentes tipos de proyectos, inspírate para hacer tu propio mapa o simplemente descubre nuevos lugares."

            }
        }

    }
}, function(err, t) {
    i18nextJquery.init(i18next, $);
    $('html').localize();
    $('title').localize();
    $("#lng").text("en");

    $('.lang-select').click(function() {
      i18next.changeLanguage(this.innerHTML);
      $("#lng").text(i18next.language);
      $('html').localize();
      $('title').localize();
    });
});